<?php
$gpics='{"gallery":[ '; 
$gpics.='{"flag":"T","picTtl":"Masterclass 2016"},	
{"flag":"P","grpTtl":"Masterclass:2016","picLarge":"17thmasterclass_1.jpg","picSmall":"17thmasterclass_1_120.jpg","picTtl":"William Cuthbertson mit Student","copy":"Foto:Sanja Stefanovic"},
{"flag":"P","grpTtl":"Masterclass:2016","picLarge":"17thmasterclass_2.jpg","picSmall":"17thmasterclass_2_120.jpg","picTtl":"William Cuthbertson mit Studenten","copy":"Foto:Sanja Stefanovic"},
{"flag":"P","grpTtl":"Masterclass:2016","picLarge":"17thmasterclass_3.jpg","picSmall":"17thmasterclass_3_120.jpg","picTtl":"William Cuthbertson mit Studenten","copy":"Foto:Sanja Stefanovic"},';
$gpics.='{"flag":"T","picTtl":"Concerts 2016"},
{"flag":"P","grpTtl":"Concerts 2016","picLarge":"2006_1.jpg","picSmall":"2006_1_120.jpg","picTtl":"Stiftung Beatus, Sigriswil, Switzerland"},
{"flag":"P","grpTtl":"Concerts 2016","picLarge":"novgorod1.png","picSmall":"novgorod1_tn.png","picTtl":"Novgorod, Russia"},
{"flag":"P","grpTtl":"Concerts 2016","picLarge":"Fr08Juli2016.jpg","picSmall":"Fr08Juli2016_tn.jpg","picTtl":"Elztal Museum Concert","copy":"Photo: Badische Zeitung, G. Zahn"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"tanzrhymiker.png","picSmall":"tanzrhymiker_120.png","picTtl":"Tanzrhythmiker Band, Waldkirch"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"masterclass2016concert.jpg","picSmall":"masterclass2016concert_120.jpg","picTtl":"Peter Feuchtwanger Memorial Concert, Waldkirch - William Cuthbertson"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_1.jpg","picSmall":"memorial2016_1_120.jpg","picTtl":"Peter Feuchtwanger Memorial Concert, Waldkirch - Agnes Joshi"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_2.jpg","picSmall":"memorial2016_2_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Daniel Kasparian"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_3.jpg","picSmall":"memorial2016_3_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Masako Kamikawa"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_4.jpg","picSmall":"memorial2016_4_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Anne Roth"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_5.jpg","picSmall":"memorial2016_5_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Manfred Seewan"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_6.jpg","picSmall":"memorial2016_6_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Ina Birk"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_7.jpg","picSmall":"memorial2016_7_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Marianne Schr&ouml;der"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_8.jpg","picSmall":"memorial2016_8_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Nina Attorf"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_9.jpg","picSmall":"memorial2016_9_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Fedra und Stefan Blido"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_10.jpg","picSmall":"memorial2016_10_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Klaus Cutik"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_11.jpg","picSmall":"memorial2016_11_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch- Sanja Stefanovic + Sophia Grech"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_13.jpg","picSmall":"memorial2016_13_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Alexander Reitenbach"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_14.jpg","picSmall":"memorial2016_14_120.jpg","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Jean-Jacques Dunki"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_15.jpg","picSmall":"memorial2016_15_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Paul Cibis und Mayuko Vetter"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_16.jpg","picSmall":"memorial2016_16_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Saeko Saito"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_17.jpg","picSmall":"memorial2016_17_120.jpg","picTtl":"Peter Feuchtwanger, Memorial Concert, Waldkirch - Andrew Kraus"},
{"flag":"P","grpTtl":"Concerts:2016","picLarge":"memorial2016_18.jpg","picSmall":"memorial2016_18_120.jpg","picTtl":"Peter Feuchtwanger  Memorial Concert, Waldkirch - Jorrit Van den Hamm"},
{"flag":"P","grpTtl":"Konzerte:2016","picLarge":"emmastratton.png","picSmall":"emmastratton_120.png","picTtl":"Peter Feuchtwanger Gedankkonzert, Waldkirch - Emma Stratton - Andaluza and Allegro de Concerto by E.Granados."},';
$gpics.='{"flag":"T","picTtl":"Concerts:2015"},	
{"flag":"P","grpTtl":"Concerts:2015","picLarge":"21april2015.jpg","picSmall":"21april2015_120.jpg",	"picTtl":"Preludes by Chopin and Scriabin","copy":"Photo:Badischer Zeitung"},	
{"flag":"P","grpTtl":"Concerts:2015","picLarge":"bz2015-1.jpg","picSmall":"bz2015-1-120.jpg","picTtl":"Benefit Concert for renovation of the Community Centre","copy":"Photo:Badischer Zeitung"}';
$gpics.=',{"flag":"T","picTtl":"Masterclass 2015"},
{"flag":"P","grpTtl":"Masterclass 2015", "picLarge":"masterclass2015_1.jpg","picSmall":"masterclass2015_1_tn.jpg","picTtl":"William mit Student"},
{"flag":"P","grpTtl":"Masterclass 2015","picLarge":"masterclass2015_2.jpg","picSmall":"masterclass2015_2_tn.jpg","picTtl":"William mit Studenten"},	
{"flag":"P","grpTtl":"Masterclass 2015", "picLarge":"masterclass2015_3.jpg","picSmall":"masterclass2015_3_tn.jpg","picTtl":"William mit Student"},	
{"flag":"P","grpTtl":"Masterclass 2015", "picLarge":"masterclass2015_4.jpg","picSmall":"masterclass2015_4_tn.jpg","picTtl":"William mit Student"},	
{"flag":"P","grpTtl":"Masterclass 2015","picLarge":"masterclass2015_5.png","picSmall":"masterclass2015_5_tn.png","picTtl":"Studenten"},	
{"flag":"P","grpTtl":"Masterclass 2015","picLarge":"masterclass2015_6.png","picSmall":"masterclass2015_6_tn.png","picTtl":"Student"},	
{"flag":"P","grpTtl":"Masterclass 2015","picLarge":"masterclass2015_11.jpg","picSmall":"masterclass2015_11_tn.jpg","picTtl":"After Party"},	
{"flag":"P","grpTtl":"Masterclass 2015",  "picLarge":"masterclass2015_7.jpg", "picSmall":"masterclass2015_7_tn.jpg","picTtl":"Abschlusskonzert. TeilnehmerInnen kriegen Blumen"},	
{"flag":"P","grpTtl":"Masterclass 2015", "picLarge":"masterclass2015_8.jpg","picSmall":"masterclass2015_8_tn.jpg","picTtl":"Stefan Blido (Feuchtwanger Übungen)"},
{"flag":"P","grpTtl":"Masterclass 2015", "picLarge":"masterclass2015_9.jpg","picSmall":"masterclass2015_9_tn.jpg","picTtl":"Und wir kriegen ein nettes Geschenk. William Cuthbertson (Klavier)"},
{"flag":"P","grpTtl":"Masterclass 2015", "picLarge":"masterclass2015_10.jpg","picSmall":"masterclass2015_10_tn.jpg","picTtl":"Martina Barufke (Alexander Technik)"}';

$gpics.=',{"flag":"T","picTtl":"Teaching:2015"},
{"flag":"P","grpTtl":"Teaching:2015","picLarge":"Vorspiel1.jpg","picSmall":"Vorspiel1_tn.jpg","picTtl":"Piano Pupil "},
{"flag":"P","grpTtl":"Teaching:2015","picLarge":"Vorspiel2.jpg","picSmall":"Vorspiel2_tn.jpg","picTtl":"Piano and Violin Pupils performing"},
{"flag":"P","grpTtl":"Teaching:2015","picLarge":"Vorspiel3.jpg","picSmall":"Vorspiel3_tn.jpg","picTtl":"Piano Pupil"},
{"flag":"P","grpTtl":"Teaching:2015","picLarge":"Abrsm1-1.jpg","picSmall":"Abrsm1-1_tn.jpg","picTtl":"Piano Pupil with ABRSM Certificate"},
{"flag":"P","grpTtl":"Teaching:2015","picLarge":"Abrsm2-1.jpg","picSmall":"Abrsm2-1_tn.jpg","picTtl":"Piano Pupil with ABRSM Certificate"}';
$gpics.=',{"flag":"T","picTtl":"Masterclass:2014"},
{"flag":"P","grpTtl":"Meisterclass:2014","picLarge":"peterfeutchtwangerKaoruMaruyamawilliam.jpg","picSmall":"peterfeutchtwangerKaoruMaruyamawilliam_tn.jpg","picTtl":"Peter Feutchtwanger,Kaoru Maruyama, William Cuthbertson"},
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"foto1.JPG","picSmall":"foto1_tn.jpg","picTtl":"Peter Feuchtwanger, William Cuthbertson and students"},
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"foto2.JPG","picSmall":"foto2_tn.jpg","picTtl":"Peter Feuchtwanger, student and William Cuthbertson"},
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"foto3.JPG","picSmall":"foto3_tn.jpg","picTtl":"William Cuthbertson and students"},	
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"foto4.JPG","picSmall":"foto4_tn.jpg","picTtl":"Peter Feuchtwanger and student"},
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"foto5.JPG","picSmall":"foto5_tn.jpg","picTtl":"Peter Feuchtwanger, William Cuthbertson and students"},
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"foto6.JPG","picSmall":"foto6_tn.jpg","picTtl":"Peter Feuchtwanger, William Cuthbertson with Student"},
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"foto7.JPG","picSmall":"foto7_tn.jpg","picTtl":"William Cuthbertson and students"},
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"foto8.JPG","picSmall":"foto8_tn.jpg","picTtl":"William Cuthbertson"},	
{"flag":"P","grpTtl":"Masterclass:2014","picLarge":"peter.feuchtwanger_teaching.jpg","picSmall":"peter.feuchtwanger_teaching_140.jpg","picTtl":"Peter Feuchtwanger teaching"}';
$gpics.=',{"flag":"T","picTtl":"Concerts:2014"},
{"flag":"P","grpTtl":"Concerts:2014","picLarge":"kulturwoche2014.jpg","picSmall":"kulturwoche2014_120.jpg","picTtl":"Waldkirch Culture Week 2014","copy":"Foto:Badische Zeitung"},
{"flag":"P","grpTtl":"Concerts:2014","picLarge":"foto9.jpg","picSmall":"foto9_120.jpg","picTtl":"Waldkirch  Musicians sing and play music of Mozart to Bob Dylan"},
{"flag":"P","grpTtl":"Concerts:2014","picLarge":"foto10.jpg","picSmall":"foto10_120.jpg","picTtl":"William Cuthbertson and Weimo Gao"},
{"flag":"P","grpTtl":"Concerts:2014","picLarge":"foto12.jpg","picSmall":"foto12_120.jpg","picTtl":"Open Air Concert with the Waldkirch Dance Band"},	
{"flag":"P","grpTtl":"Concerts:2014","picLarge":"22october2014.jpg","picSmall":"22october2014_120.jpg","picTtl":"William Cuthbertson with Singer"},
{"flag":"P","grpTtl":"Concerts:2014","picLarge":"chopin.jpg","picSmall":"chopin_120.jpg","picTtl":"Chopin Concert"},
{"flag":"P","grpTtl":"Concerts:2014","picLarge":"concert_fb.jpg","picSmall":"concert_fb_120.jpg","picTtl":"Weimo Gao"},
{"flag":"P","grpTtl":"Concerts:2014","picLarge":"chopinetuden.jpg", "picSmall":"chopinetuden_120.jpg","picTtl":"Chopin Etudes","copy":"Foto:Badische Zeitung"}';
$gpics.=',{"flag":"T","picTtl":"Masterclass 2013"},	
{"flag":"P","grpTtl":"Masterclass:2013","picLarge":"14thMasterclass.jpg","picSmall":"14thMasterclass_120.jpg","picTtl":"Daniel Kasparian, Agnes Joshi-Meili, Elisa Neugart, Professor Peter Feuchtwanger, Masako Kamikawa, Urs Weilenmann and Christian Loeschke","copy":"Photo: Badische Zeitung, Eberhard Weiss"},
{"flag":"P","grpTtl":"Masterclass:2013","picLarge":"14thMasterclass-2.jpg","picSmall":"14thMasterclass-2_120.jpg","picTtl":"Masako Kamikawa plays Chopins Rondo in E flat major","copy":"Foto: Badische Zeitung, Eberhard Weiss"}';
$gpics.=',{"flag":"T","picTtl":"Concerts:2013"},
{"flag":"P","grpTtl":"Concerts:2013","picLarge":"foto11.jpg","picSmall":"foto11_120.jpg","picTtl":"Words by Wilhelm Busch, Music by William Cuthbertson"},	
{"flag":"T","picTtl":"Concerts:2012"},	 
{"flag":"P","grpTtl":"Concerts:2013","picLarge":"IMG_2402.JPG","picSmall":"IMG_2402_120.jpg","picTtl":"Nov.26th 2012 in St. James, Piccadilly, London, England,William plays Beethovens Hammerklavier-Sonate"},
{"flag":"P","grpTtl":"Concerts:2012", "picLarge":"WilhelmBuschAbend.jpg","picSmall":"WilhelmBuschAbend_120.jpg","picTtl":"Wilhelm Busch Evening"},
{"flag":"P","grpTtl":"Concert:2012","picLarge":"yikisun.jpg","picSmall":"yikisun_120.jpg","picTtl":"Concert with mit Sun Yiqi and William Cuthbertson"},
{"flag":"P","grpTtl":"Concert:2012","picLarge":"Gershwin2.JPG","picSmall":"Gershwin2_120.JPG","picTtl":"Rhapsody in Blue"},
{"flag":"P","grpTtl":"Concert:2012","picLarge":"NeuesBild.JPG","picSmall":"NeuesBild_120.JPG","picTtl":"Rhapsody in Blue"}';
$gpics.=']}';
?>